### ISSUE TITLE
add colspan support for footer

### ISSUE THREAD

**Issue by chipco** [DataTables/Buttons#63] opened 2016-01-04 19:52 UTC
When printing a table with colspan in footer the cell is repeated with no colspan.

Example:

``` html
<tfoot>
    <tr>
        <th colspan="3">a</th>
        <th>b</th>
    </tr>
</tfoot>
```

results in 

| a | a | a | b |
| --- | --- | --- | --- |

**Comment by DataTables** [comment] 2016-01-05 09:14
I think this is a duplicate of #60. The issue is that there is no way to represent the colspan in CSV or TSV.

**Comment by chipco** [comment] 2016-01-05 09:21
Indeed, but it should work for print and pdf.

Atm I'm using a customize for print:

```js
customize: function (win) {
	var footer = $('tfoot');
	if (footer.length > 0) {
		var exportFooter = $(win.document.body).find('thead:eq(1)');
		exportFooter.after(footer.clone());
		exportFooter.remove();
	}
}
```

*Note the `thead:eq(1)` should be replaced by `thead` when the [fix](https://github.com/DataTables/Buttons/commit/95b66858fa4c745bc6170ff0eb5767384d21982b) is released.*

**Comment by vol7ron** [comment] 2016-03-05 19:32
In my pull request: https://github.com/DataTables/Buttons/pull/74 I introduce the ability to modify the data before it is exported, for instance in CSV and TSV.  In my [example](http://live.datatables.net/sajaxota/1/edit) I show one approach to dealing with colspans in those cases.

While it does not automate things for the developer, it at least releases some control to the developer, to modify the exported data.  In the future you can add formatting options; for instance:

- ***colspans-repeat*** (boolean) :  
optional format; when a colspan is encountered, its value will be repeated for _n_ number of columns in the span (alternative is to fill columns with empty strings, as in my example)
- ***colspans-col-value-first*** | ***colspans-col-value-last*** (boolean) ;  
***colspans-col-value-position*** (integer) :  
optional format; when colspan value does not repeat, let the user decide what cell the value should appear in.  
 - If *first* is *true*, then the value will appear in the first column, followed by blank strings.
 - If *last* is *true*, then the value will appear in the last column, with empty strings appearing before it.
 - If the *position* is selected the value will appear in that respective column within the colspan, with empty strings in the columns that come before and after for the duration of the span.

**Comment by chipco** [comment] 2016-03-24 19:19
Thanks @vol7ron, that's a great idea. Being able to customize the data in geneal is the way to go in my opinion. For example in some cases I want to export footers with more than one row, but the default behavior is to export only the first. Similarly for headers, only the last table row is exported now.

**Comment by inspira-repo** [comment] 2021-03-02 08:13
> Indeed, but it should work for print and pdf.
> 
> Atm I'm using a customize for print:
> 
> ```js
> customize: function (win) {
>     var footer = $('tfoot');
>     if (footer.length > 0) {
>         var exportFooter = $(win.document.body).find('thead:eq(1)');
>         exportFooter.after(footer.clone());
>         exportFooter.remove();
>     }
> }
> ```
> 
> _Note the `thead:eq(1)` should be replaced by `tfoot` when the [fix](https://github.com/DataTables/Buttons/commit/95b66858fa4c745bc6170ff0eb5767384d21982b) is released._

For pdf this is not working, "Uncaught TypeError: Cannot read property 'body' of undefined" this error is coming in 
"var exportFooter = $(win.document.body).find('tfoot:eq(1)');"

**Comment by AllanJard** [comment] 2023-10-17 14:33
This has finally been done and will ship in Buttons 3 alongside DataTables 2.

**Closed by AllanJard** 2023-10-17 14:33 UTC
