### ISSUE TITLE
Feature Request: Export Header / Footer options

### ISSUE THREAD

**Issue by joe-meyer** [DataTables/Buttons#36] opened 2015-09-29 15:20 UTC
Scenario: I'm currently using ajax in order to populate my datatables based upon some "fancy" parameter selector. So a user is picking selection criteria for the report. Now they want to export their data to excel / csv, etc etc. Unfortunately, when they do that, they have no way of telling what their selection criteria was upon export, so when they go back to that spreadsheet a week from now they might not have any idea what they are looking at.

I think it would be ideal to provide some functionality for including an export header / footer option. Even if it's just assigning some plain text to be included when present would be useful and ideally this should be able to be changed through an API call so that the header / footer could be changed as part of an ajax callback function.

**Comment by DataTables** [comment] 2015-09-29 15:26
Might be worth looking at #29 for discussion on how this might be done if you haven't already. Going to close as a duplicate of #29.

**Closed by DataTables** 2015-09-29 15:26 UTC
