### ISSUE TITLE
add support for colspan in tfoot when exporting

### ISSUE THREAD

**Issue by chipco** [DataTables/Buttons#66] opened 2016-01-05 09:05 UTC
At the moment any colspan in the table footer is replaced by several single cells, repeating the content of the multi-cell, which is not desirable. The exported table should maintain the structure of the original table.

Test case: https://jsfiddle.net/Lr77dgmt/3/

**Comment by DataTables** [comment] 2016-01-05 09:14
Looks like a duplicate of #63.

**Closed by DataTables** 2016-01-05 09:14 UTC

**Comment by chipco** [comment] 2016-01-05 09:15
sorry, forgot I posted that issue already
