### ISSUE TITLE
Performance issue of exporting

### ISSUE THREAD

**Issue by martin-liu** [DataTables/Buttons#100] opened 2016-07-26 22:49 UTC
I tested exporting to csv file with 50000 rows (50000 \* 6), see http://jsfiddle.net/doqd5n0r/ . It need nearly 20 secs to execute and get file generated.

Here's profiling result from chrome:
![image](https://cloud.githubusercontent.com/assets/1459760/17158022/4a2a92a2-5348-11e6-8697-716d5fa90ac4.png)

![image](https://cloud.githubusercontent.com/assets/1459760/17158085/a0ef3ad4-5348-11e6-9e81-f0eb5e6ef5ed.png)

Is there anyway to improve it?

**Comment by DataTables** [comment] 2016-07-27 08:51
Thanks for the test case. There almost certainly will be a way to improve the performance, but I'm afraid I don't have an immediate way to do so. I'll leave this open until I have a chance to look at this in details (I'm not sure when that will be, but hopefully not too far away).

**Comment by msvova** [comment] 2017-01-10 13:37
Hello!

Is it the same issue with exoporting to Excel http://jsfiddle.net/u45yrqxe/ ? It takes at about 10 sec to export 2000*6 rows.

**Comment by DataTables** [comment] 2017-01-10 14:18
Very probably.

**Comment by msvova** [comment] 2017-01-10 14:31
Are you planning to fix this issue?

**Comment by DataTables** [comment] 2017-01-10 14:46
Yes. But I don't have a time frame for it yet due to working on other things.

**Comment by DataTables** [comment] 2017-04-14 20:10
[Fixed here](https://github.com/DataTables/DataTablesSrc/commit/5300387cfec28cc7f0182166894833583cdcfda4). Will be included in DataTables 1.10.14 which will ship next week.

**Closed by DataTables** 2017-04-14 20:10 UTC

**Comment by msvendsen** [comment] 2019-04-24 11:07
Hi,
We are also seeing performance issues. I have made a JSFiddle with a test scenario with updated libs. It takes half minute to export 20k rows.
We have tables with +100k rows and would like an export function (CSV export takes same amount of time generating than an Excel)

http://jsfiddle.net/eLtf8aq7/1/

Any ideas? THANKS!!!

**Comment by DataTables** [comment] 2019-04-24 11:09
There was a regression between .16 and .17 for DataTables which is still in the current release.

[Try the nightly version](https://datatables.net/download/nightly) which should fix it.

**Comment by msvendsen** [comment] 2019-04-24 11:13
But I'm using .19.. :)
I'll try the nightly version.
Thanks for Quick reply!

**Comment by DataTables** [comment] 2019-04-24 11:14
Yes, as I said, its still in the current release :-). The nightly should fix it. And if it doesn't please post a support request in the forums with a link to a test case.

**Comment by msvendsen** [comment] 2019-04-24 11:22
Thanks. I just tested with the nightly build.
Before opening a support request - what execution time should I expect for 20k rows? 100k rows?
THANKS!

**Comment by DataTables** [comment] 2019-04-24 11:25
A few seconds I would guess. But it depends on a lot of factors like if you have any renderers.
